# https://taskfile.dev

version: '3'

tasks:
  dev:
    cmds:
      - air
    silent: true
  db-migrate:
    cmds:
      - go run migrations/migrate.go up
    silent: true
  db-rollback:
    cmds:
      - go run migrations/migrate.go down
    silent: true
  db-status:
    cmds:
      - go run migrations/migrate.go status
    silent: true
